name: get-gke-credentials Integration

on:
  push:
    branches:
    - 'main'
    - 'add-wif'
  pull_request:

concurrency:
  group: '${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  gcloud:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    name: with setup-gcloud & kubectl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master # Set up ADC for credentials
      with:
        service_account_key: ${{ secrets.GET_GKE_CRED_SA_KEY_JSON }}
        export_default_credentials: true
    - id: build
      name: Build dist
      run: |-
        npm install
        npm run build
    - id: get-kubeconfig
      uses: ./
      with:
        project_id: ${{ secrets.GET_GKE_CRED_PROJECT }}
        cluster_name: ${{ secrets.GET_GKE_CRED_CLUSTER_NAME }}
        location: ${{ secrets.GET_GKE_CRED_CLUSTER_LOCATION }}
        use_auth_provider: true
    - name: test-kubectl # Use kubectl with the generated kubeconfig to auth and list pods. There should be no pods in the default ns.
      run: |
        pods=$(kubectl get pods -o=jsonpath='{$.items[*]}')
        if [ -n "$pods" ]
        then
            echo "Expected no pods. Got ${pods}"
            exit 1
        fi

  base64:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    name: with base64 creds & API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      run: |-
        npm install
        npm run build
    - id: get-kubeconfig
      uses: ./
      with:
        project_id: ${{ secrets.GET_GKE_CRED_PROJECT }}
        credentials: ${{ secrets.GET_GKE_CRED_SA_KEY_B64 }}
        cluster_name: ${{ secrets.GET_GKE_CRED_CLUSTER_NAME }}
        location: ${{ secrets.GET_GKE_CRED_CLUSTER_LOCATION }}
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
    - name: integration tests
      run: npm run e2e-tests

  json-api:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    name: with json creds & API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      run: |-
        npm install
        npm run build
    - id: get-kubeconfig
      uses: ./
      with:
        project_id: ${{ secrets.GET_GKE_CRED_PROJECT }}
        credentials: ${{ secrets.GET_GKE_CRED_SA_KEY_JSON }}
        cluster_name: ${{ secrets.GET_GKE_CRED_CLUSTER_NAME }}
        location: ${{ secrets.GET_GKE_CRED_CLUSTER_LOCATION }}
    - run: npm install
    - name: integration tests
      run: npm run e2e-tests

  json-kubectl:
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    name: with json creds & kubectl
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      run: |-
        npm install
        npm run build
    - id: get-kubeconfig
      uses: ./
      with:
        project_id: ${{ secrets.GET_GKE_CRED_PROJECT }}
        credentials: ${{ secrets.GET_GKE_CRED_SA_KEY_JSON }}
        cluster_name: ${{ secrets.GET_GKE_CRED_CLUSTER_NAME }}
        location: ${{ secrets.GET_GKE_CRED_CLUSTER_LOCATION }}
    - name: test-kubectl # Use kubectl with the generated kubeconfig to auth and list pods. There should be no pods in the default ns.
      run: |
        pods=$(kubectl get pods -o=jsonpath='{$.items[*]}')
        if [ -n "$pods" ]
        then
            echo "Expected no pods. Got ${pods}"
            exit 1
        fi

  wif:
    permissions:
      contents: 'read'
      id-token: 'write'
    if: ${{ github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name && github.actor != 'dependabot[bot]' }}
    name: with wif
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@main
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER_NAME }}
        service_account: ${{ secrets.GET_GKE_CRED_SA_EMAIL }}
        create_credentials_file: true
    - id: build
      name: Build dist
      run: |-
        npm install
        npm run build
    - id: get-kubeconfig
      uses: ./
      with:
        project_id: ${{ secrets.GET_GKE_CRED_PROJECT }}
        cluster_name: ${{ secrets.GET_GKE_CRED_CLUSTER_NAME }}
        location: ${{ secrets.GET_GKE_CRED_CLUSTER_LOCATION }}
    - name: test-kubectl # Use kubectl with the generated kubeconfig to auth and list pods. There should be no pods in the default ns.
      run: |
        pods=$(kubectl get pods -o=jsonpath='{$.items[*]}')
        if [ -n "$pods" ]
        then
            echo "Expected no pods. Got ${pods}"
            exit 1
        fi